package com.datacenter.bean;

import java.util.Date;

public class Chinesenews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.model
     *
     * @mbggenerated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.gmt_created
     *
     * @mbggenerated
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.sj
     *
     * @mbggenerated
     */
    private String sj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chinesenews.idstr
     *
     * @mbggenerated
     */
    private String idstr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.id
     *
     * @return the value of chinesenews.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.id
     *
     * @param id the value for chinesenews.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.url
     *
     * @return the value of chinesenews.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.url
     *
     * @param url the value for chinesenews.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.title
     *
     * @return the value of chinesenews.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.title
     *
     * @param title the value for chinesenews.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.date
     *
     * @return the value of chinesenews.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.date
     *
     * @param date the value for chinesenews.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.model
     *
     * @return the value of chinesenews.model
     *
     * @mbggenerated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.model
     *
     * @param model the value for chinesenews.model
     *
     * @mbggenerated
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.gmt_created
     *
     * @return the value of chinesenews.gmt_created
     *
     * @mbggenerated
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.gmt_created
     *
     * @param gmtCreated the value for chinesenews.gmt_created
     *
     * @mbggenerated
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.gmt_modified
     *
     * @return the value of chinesenews.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.gmt_modified
     *
     * @param gmtModified the value for chinesenews.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.type
     *
     * @return the value of chinesenews.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.type
     *
     * @param type the value for chinesenews.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.sj
     *
     * @return the value of chinesenews.sj
     *
     * @mbggenerated
     */
    public String getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.sj
     *
     * @param sj the value for chinesenews.sj
     *
     * @mbggenerated
     */
    public void setSj(String sj) {
        this.sj = sj == null ? null : sj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chinesenews.idstr
     *
     * @return the value of chinesenews.idstr
     *
     * @mbggenerated
     */
    public String getIdstr() {
        return idstr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chinesenews.idstr
     *
     * @param idstr the value for chinesenews.idstr
     *
     * @mbggenerated
     */
    public void setIdstr(String idstr) {
        this.idstr = idstr == null ? null : idstr.trim();
    }
}