package com.datacenter.bean;

import java.util.ArrayList;
import java.util.List;

public class ConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public ConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConfigIdIsNull() {
            addCriterion("config_id is null");
            return (Criteria) this;
        }

        public Criteria andConfigIdIsNotNull() {
            addCriterion("config_id is not null");
            return (Criteria) this;
        }

        public Criteria andConfigIdEqualTo(Integer value) {
            addCriterion("config_id =", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotEqualTo(Integer value) {
            addCriterion("config_id <>", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThan(Integer value) {
            addCriterion("config_id >", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("config_id >=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThan(Integer value) {
            addCriterion("config_id <", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThanOrEqualTo(Integer value) {
            addCriterion("config_id <=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdIn(List<Integer> values) {
            addCriterion("config_id in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotIn(List<Integer> values) {
            addCriterion("config_id not in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdBetween(Integer value1, Integer value2) {
            addCriterion("config_id between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotBetween(Integer value1, Integer value2) {
            addCriterion("config_id not between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigTitleIsNull() {
            addCriterion("config_title is null");
            return (Criteria) this;
        }

        public Criteria andConfigTitleIsNotNull() {
            addCriterion("config_title is not null");
            return (Criteria) this;
        }

        public Criteria andConfigTitleEqualTo(String value) {
            addCriterion("config_title =", value, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleNotEqualTo(String value) {
            addCriterion("config_title <>", value, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleGreaterThan(String value) {
            addCriterion("config_title >", value, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleGreaterThanOrEqualTo(String value) {
            addCriterion("config_title >=", value, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleLessThan(String value) {
            addCriterion("config_title <", value, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleLessThanOrEqualTo(String value) {
            addCriterion("config_title <=", value, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleLike(String value) {
            addCriterion("config_title like", value, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleNotLike(String value) {
            addCriterion("config_title not like", value, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleIn(List<String> values) {
            addCriterion("config_title in", values, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleNotIn(List<String> values) {
            addCriterion("config_title not in", values, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleBetween(String value1, String value2) {
            addCriterion("config_title between", value1, value2, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigTitleNotBetween(String value1, String value2) {
            addCriterion("config_title not between", value1, value2, "configTitle");
            return (Criteria) this;
        }

        public Criteria andConfigUrlIsNull() {
            addCriterion("config_url is null");
            return (Criteria) this;
        }

        public Criteria andConfigUrlIsNotNull() {
            addCriterion("config_url is not null");
            return (Criteria) this;
        }

        public Criteria andConfigUrlEqualTo(String value) {
            addCriterion("config_url =", value, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlNotEqualTo(String value) {
            addCriterion("config_url <>", value, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlGreaterThan(String value) {
            addCriterion("config_url >", value, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlGreaterThanOrEqualTo(String value) {
            addCriterion("config_url >=", value, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlLessThan(String value) {
            addCriterion("config_url <", value, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlLessThanOrEqualTo(String value) {
            addCriterion("config_url <=", value, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlLike(String value) {
            addCriterion("config_url like", value, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlNotLike(String value) {
            addCriterion("config_url not like", value, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlIn(List<String> values) {
            addCriterion("config_url in", values, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlNotIn(List<String> values) {
            addCriterion("config_url not in", values, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlBetween(String value1, String value2) {
            addCriterion("config_url between", value1, value2, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigUrlNotBetween(String value1, String value2) {
            addCriterion("config_url not between", value1, value2, "configUrl");
            return (Criteria) this;
        }

        public Criteria andConfigModelIsNull() {
            addCriterion("config_model is null");
            return (Criteria) this;
        }

        public Criteria andConfigModelIsNotNull() {
            addCriterion("config_model is not null");
            return (Criteria) this;
        }

        public Criteria andConfigModelEqualTo(String value) {
            addCriterion("config_model =", value, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelNotEqualTo(String value) {
            addCriterion("config_model <>", value, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelGreaterThan(String value) {
            addCriterion("config_model >", value, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelGreaterThanOrEqualTo(String value) {
            addCriterion("config_model >=", value, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelLessThan(String value) {
            addCriterion("config_model <", value, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelLessThanOrEqualTo(String value) {
            addCriterion("config_model <=", value, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelLike(String value) {
            addCriterion("config_model like", value, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelNotLike(String value) {
            addCriterion("config_model not like", value, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelIn(List<String> values) {
            addCriterion("config_model in", values, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelNotIn(List<String> values) {
            addCriterion("config_model not in", values, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelBetween(String value1, String value2) {
            addCriterion("config_model between", value1, value2, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigModelNotBetween(String value1, String value2) {
            addCriterion("config_model not between", value1, value2, "configModel");
            return (Criteria) this;
        }

        public Criteria andConfigStartIsNull() {
            addCriterion("config_start is null");
            return (Criteria) this;
        }

        public Criteria andConfigStartIsNotNull() {
            addCriterion("config_start is not null");
            return (Criteria) this;
        }

        public Criteria andConfigStartEqualTo(String value) {
            addCriterion("config_start =", value, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartNotEqualTo(String value) {
            addCriterion("config_start <>", value, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartGreaterThan(String value) {
            addCriterion("config_start >", value, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartGreaterThanOrEqualTo(String value) {
            addCriterion("config_start >=", value, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartLessThan(String value) {
            addCriterion("config_start <", value, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartLessThanOrEqualTo(String value) {
            addCriterion("config_start <=", value, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartLike(String value) {
            addCriterion("config_start like", value, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartNotLike(String value) {
            addCriterion("config_start not like", value, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartIn(List<String> values) {
            addCriterion("config_start in", values, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartNotIn(List<String> values) {
            addCriterion("config_start not in", values, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartBetween(String value1, String value2) {
            addCriterion("config_start between", value1, value2, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStartNotBetween(String value1, String value2) {
            addCriterion("config_start not between", value1, value2, "configStart");
            return (Criteria) this;
        }

        public Criteria andConfigStopIsNull() {
            addCriterion("config_stop is null");
            return (Criteria) this;
        }

        public Criteria andConfigStopIsNotNull() {
            addCriterion("config_stop is not null");
            return (Criteria) this;
        }

        public Criteria andConfigStopEqualTo(String value) {
            addCriterion("config_stop =", value, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopNotEqualTo(String value) {
            addCriterion("config_stop <>", value, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopGreaterThan(String value) {
            addCriterion("config_stop >", value, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopGreaterThanOrEqualTo(String value) {
            addCriterion("config_stop >=", value, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopLessThan(String value) {
            addCriterion("config_stop <", value, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopLessThanOrEqualTo(String value) {
            addCriterion("config_stop <=", value, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopLike(String value) {
            addCriterion("config_stop like", value, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopNotLike(String value) {
            addCriterion("config_stop not like", value, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopIn(List<String> values) {
            addCriterion("config_stop in", values, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopNotIn(List<String> values) {
            addCriterion("config_stop not in", values, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopBetween(String value1, String value2) {
            addCriterion("config_stop between", value1, value2, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigStopNotBetween(String value1, String value2) {
            addCriterion("config_stop not between", value1, value2, "configStop");
            return (Criteria) this;
        }

        public Criteria andConfigDaysIsNull() {
            addCriterion("config_days is null");
            return (Criteria) this;
        }

        public Criteria andConfigDaysIsNotNull() {
            addCriterion("config_days is not null");
            return (Criteria) this;
        }

        public Criteria andConfigDaysEqualTo(Integer value) {
            addCriterion("config_days =", value, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigDaysNotEqualTo(Integer value) {
            addCriterion("config_days <>", value, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigDaysGreaterThan(Integer value) {
            addCriterion("config_days >", value, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigDaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("config_days >=", value, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigDaysLessThan(Integer value) {
            addCriterion("config_days <", value, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigDaysLessThanOrEqualTo(Integer value) {
            addCriterion("config_days <=", value, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigDaysIn(List<Integer> values) {
            addCriterion("config_days in", values, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigDaysNotIn(List<Integer> values) {
            addCriterion("config_days not in", values, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigDaysBetween(Integer value1, Integer value2) {
            addCriterion("config_days between", value1, value2, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigDaysNotBetween(Integer value1, Integer value2) {
            addCriterion("config_days not between", value1, value2, "configDays");
            return (Criteria) this;
        }

        public Criteria andConfigStateIsNull() {
            addCriterion("config_state is null");
            return (Criteria) this;
        }

        public Criteria andConfigStateIsNotNull() {
            addCriterion("config_state is not null");
            return (Criteria) this;
        }

        public Criteria andConfigStateEqualTo(String value) {
            addCriterion("config_state =", value, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateNotEqualTo(String value) {
            addCriterion("config_state <>", value, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateGreaterThan(String value) {
            addCriterion("config_state >", value, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateGreaterThanOrEqualTo(String value) {
            addCriterion("config_state >=", value, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateLessThan(String value) {
            addCriterion("config_state <", value, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateLessThanOrEqualTo(String value) {
            addCriterion("config_state <=", value, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateLike(String value) {
            addCriterion("config_state like", value, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateNotLike(String value) {
            addCriterion("config_state not like", value, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateIn(List<String> values) {
            addCriterion("config_state in", values, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateNotIn(List<String> values) {
            addCriterion("config_state not in", values, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateBetween(String value1, String value2) {
            addCriterion("config_state between", value1, value2, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigStateNotBetween(String value1, String value2) {
            addCriterion("config_state not between", value1, value2, "configState");
            return (Criteria) this;
        }

        public Criteria andConfigTimeIsNull() {
            addCriterion("config_time is null");
            return (Criteria) this;
        }

        public Criteria andConfigTimeIsNotNull() {
            addCriterion("config_time is not null");
            return (Criteria) this;
        }

        public Criteria andConfigTimeEqualTo(String value) {
            addCriterion("config_time =", value, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeNotEqualTo(String value) {
            addCriterion("config_time <>", value, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeGreaterThan(String value) {
            addCriterion("config_time >", value, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeGreaterThanOrEqualTo(String value) {
            addCriterion("config_time >=", value, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeLessThan(String value) {
            addCriterion("config_time <", value, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeLessThanOrEqualTo(String value) {
            addCriterion("config_time <=", value, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeLike(String value) {
            addCriterion("config_time like", value, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeNotLike(String value) {
            addCriterion("config_time not like", value, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeIn(List<String> values) {
            addCriterion("config_time in", values, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeNotIn(List<String> values) {
            addCriterion("config_time not in", values, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeBetween(String value1, String value2) {
            addCriterion("config_time between", value1, value2, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigTimeNotBetween(String value1, String value2) {
            addCriterion("config_time not between", value1, value2, "configTime");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoIsNull() {
            addCriterion("config_remarktwo is null");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoIsNotNull() {
            addCriterion("config_remarktwo is not null");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoEqualTo(String value) {
            addCriterion("config_remarktwo =", value, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoNotEqualTo(String value) {
            addCriterion("config_remarktwo <>", value, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoGreaterThan(String value) {
            addCriterion("config_remarktwo >", value, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoGreaterThanOrEqualTo(String value) {
            addCriterion("config_remarktwo >=", value, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoLessThan(String value) {
            addCriterion("config_remarktwo <", value, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoLessThanOrEqualTo(String value) {
            addCriterion("config_remarktwo <=", value, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoLike(String value) {
            addCriterion("config_remarktwo like", value, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoNotLike(String value) {
            addCriterion("config_remarktwo not like", value, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoIn(List<String> values) {
            addCriterion("config_remarktwo in", values, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoNotIn(List<String> values) {
            addCriterion("config_remarktwo not in", values, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoBetween(String value1, String value2) {
            addCriterion("config_remarktwo between", value1, value2, "configRemarktwo");
            return (Criteria) this;
        }

        public Criteria andConfigRemarktwoNotBetween(String value1, String value2) {
            addCriterion("config_remarktwo not between", value1, value2, "configRemarktwo");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}