package com.datacenter.bean;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import lombok.experimental.Accessors;

@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@Accessors(chain = true)
public class Countnews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countnews.count_id
     *
     * @mbggenerated
     */
    private Integer countId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countnews.count_all
     *
     * @mbggenerated
     */
    @JsonIgnore
    private String countAll;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countnews.count_sum
     *
     * @mbggenerated
     */
    private Integer countSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countnews.count_remarkone
     *
     * @mbggenerated
     */
    private Integer countRemarkone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column countnews.count_remarktwo
     *
     * @mbggenerated
     */
    @JsonIgnore
    private String countRemarktwo;

    /**
     * 表示的该行记录是根据抽样countDay天的数据估算得出的
     */
    @JsonIgnore
    private int countDay;




}