package com.datacenter.bean;

public class Detection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.re_id
     *
     * @mbggenerated
     */
    private Integer reId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.re_name
     *
     * @mbggenerated
     */
    private String reName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.re_url
     *
     * @mbggenerated
     */
    private String reUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.re_surl
     *
     * @mbggenerated
     */
    private String reSurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.re_addtime
     *
     * @mbggenerated
     */
    private String reAddtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.re_item
     *
     * @mbggenerated
     */
    private String reItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.re_element
     *
     * @mbggenerated
     */
    private String reElement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.re_tree
     *
     * @mbggenerated
     */
    private String reTree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detection.re_limit
     *
     * @mbggenerated
     */
    private Integer reLimit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.re_id
     *
     * @return the value of detection.re_id
     *
     * @mbggenerated
     */
    public Integer getReId() {
        return reId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.re_id
     *
     * @param reId the value for detection.re_id
     *
     * @mbggenerated
     */
    public void setReId(Integer reId) {
        this.reId = reId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.re_name
     *
     * @return the value of detection.re_name
     *
     * @mbggenerated
     */
    public String getReName() {
        return reName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.re_name
     *
     * @param reName the value for detection.re_name
     *
     * @mbggenerated
     */
    public void setReName(String reName) {
        this.reName = reName == null ? null : reName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.re_url
     *
     * @return the value of detection.re_url
     *
     * @mbggenerated
     */
    public String getReUrl() {
        return reUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.re_url
     *
     * @param reUrl the value for detection.re_url
     *
     * @mbggenerated
     */
    public void setReUrl(String reUrl) {
        this.reUrl = reUrl == null ? null : reUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.re_surl
     *
     * @return the value of detection.re_surl
     *
     * @mbggenerated
     */
    public String getReSurl() {
        return reSurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.re_surl
     *
     * @param reSurl the value for detection.re_surl
     *
     * @mbggenerated
     */
    public void setReSurl(String reSurl) {
        this.reSurl = reSurl == null ? null : reSurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.re_addtime
     *
     * @return the value of detection.re_addtime
     *
     * @mbggenerated
     */
    public String getReAddtime() {
        return reAddtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.re_addtime
     *
     * @param reAddtime the value for detection.re_addtime
     *
     * @mbggenerated
     */
    public void setReAddtime(String reAddtime) {
        this.reAddtime = reAddtime == null ? null : reAddtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.re_item
     *
     * @return the value of detection.re_item
     *
     * @mbggenerated
     */
    public String getReItem() {
        return reItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.re_item
     *
     * @param reItem the value for detection.re_item
     *
     * @mbggenerated
     */
    public void setReItem(String reItem) {
        this.reItem = reItem == null ? null : reItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.re_element
     *
     * @return the value of detection.re_element
     *
     * @mbggenerated
     */
    public String getReElement() {
        return reElement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.re_element
     *
     * @param reElement the value for detection.re_element
     *
     * @mbggenerated
     */
    public void setReElement(String reElement) {
        this.reElement = reElement == null ? null : reElement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.re_tree
     *
     * @return the value of detection.re_tree
     *
     * @mbggenerated
     */
    public String getReTree() {
        return reTree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.re_tree
     *
     * @param reTree the value for detection.re_tree
     *
     * @mbggenerated
     */
    public void setReTree(String reTree) {
        this.reTree = reTree == null ? null : reTree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detection.re_limit
     *
     * @return the value of detection.re_limit
     *
     * @mbggenerated
     */
    public Integer getReLimit() {
        return reLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detection.re_limit
     *
     * @param reLimit the value for detection.re_limit
     *
     * @mbggenerated
     */
    public void setReLimit(Integer reLimit) {
        this.reLimit = reLimit;
    }
}