package com.datacenter.bean;

import java.util.ArrayList;
import java.util.List;

public class DetectionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detection
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detection
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table detection
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public DetectionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detection
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReIdIsNull() {
            addCriterion("re_id is null");
            return (Criteria) this;
        }

        public Criteria andReIdIsNotNull() {
            addCriterion("re_id is not null");
            return (Criteria) this;
        }

        public Criteria andReIdEqualTo(Integer value) {
            addCriterion("re_id =", value, "reId");
            return (Criteria) this;
        }

        public Criteria andReIdNotEqualTo(Integer value) {
            addCriterion("re_id <>", value, "reId");
            return (Criteria) this;
        }

        public Criteria andReIdGreaterThan(Integer value) {
            addCriterion("re_id >", value, "reId");
            return (Criteria) this;
        }

        public Criteria andReIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("re_id >=", value, "reId");
            return (Criteria) this;
        }

        public Criteria andReIdLessThan(Integer value) {
            addCriterion("re_id <", value, "reId");
            return (Criteria) this;
        }

        public Criteria andReIdLessThanOrEqualTo(Integer value) {
            addCriterion("re_id <=", value, "reId");
            return (Criteria) this;
        }

        public Criteria andReIdIn(List<Integer> values) {
            addCriterion("re_id in", values, "reId");
            return (Criteria) this;
        }

        public Criteria andReIdNotIn(List<Integer> values) {
            addCriterion("re_id not in", values, "reId");
            return (Criteria) this;
        }

        public Criteria andReIdBetween(Integer value1, Integer value2) {
            addCriterion("re_id between", value1, value2, "reId");
            return (Criteria) this;
        }

        public Criteria andReIdNotBetween(Integer value1, Integer value2) {
            addCriterion("re_id not between", value1, value2, "reId");
            return (Criteria) this;
        }

        public Criteria andReNameIsNull() {
            addCriterion("re_name is null");
            return (Criteria) this;
        }

        public Criteria andReNameIsNotNull() {
            addCriterion("re_name is not null");
            return (Criteria) this;
        }

        public Criteria andReNameEqualTo(String value) {
            addCriterion("re_name =", value, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameNotEqualTo(String value) {
            addCriterion("re_name <>", value, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameGreaterThan(String value) {
            addCriterion("re_name >", value, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameGreaterThanOrEqualTo(String value) {
            addCriterion("re_name >=", value, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameLessThan(String value) {
            addCriterion("re_name <", value, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameLessThanOrEqualTo(String value) {
            addCriterion("re_name <=", value, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameLike(String value) {
            addCriterion("re_name like", value, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameNotLike(String value) {
            addCriterion("re_name not like", value, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameIn(List<String> values) {
            addCriterion("re_name in", values, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameNotIn(List<String> values) {
            addCriterion("re_name not in", values, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameBetween(String value1, String value2) {
            addCriterion("re_name between", value1, value2, "reName");
            return (Criteria) this;
        }

        public Criteria andReNameNotBetween(String value1, String value2) {
            addCriterion("re_name not between", value1, value2, "reName");
            return (Criteria) this;
        }

        public Criteria andReUrlIsNull() {
            addCriterion("re_url is null");
            return (Criteria) this;
        }

        public Criteria andReUrlIsNotNull() {
            addCriterion("re_url is not null");
            return (Criteria) this;
        }

        public Criteria andReUrlEqualTo(String value) {
            addCriterion("re_url =", value, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlNotEqualTo(String value) {
            addCriterion("re_url <>", value, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlGreaterThan(String value) {
            addCriterion("re_url >", value, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlGreaterThanOrEqualTo(String value) {
            addCriterion("re_url >=", value, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlLessThan(String value) {
            addCriterion("re_url <", value, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlLessThanOrEqualTo(String value) {
            addCriterion("re_url <=", value, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlLike(String value) {
            addCriterion("re_url like", value, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlNotLike(String value) {
            addCriterion("re_url not like", value, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlIn(List<String> values) {
            addCriterion("re_url in", values, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlNotIn(List<String> values) {
            addCriterion("re_url not in", values, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlBetween(String value1, String value2) {
            addCriterion("re_url between", value1, value2, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReUrlNotBetween(String value1, String value2) {
            addCriterion("re_url not between", value1, value2, "reUrl");
            return (Criteria) this;
        }

        public Criteria andReSurlIsNull() {
            addCriterion("re_surl is null");
            return (Criteria) this;
        }

        public Criteria andReSurlIsNotNull() {
            addCriterion("re_surl is not null");
            return (Criteria) this;
        }

        public Criteria andReSurlEqualTo(String value) {
            addCriterion("re_surl =", value, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlNotEqualTo(String value) {
            addCriterion("re_surl <>", value, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlGreaterThan(String value) {
            addCriterion("re_surl >", value, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlGreaterThanOrEqualTo(String value) {
            addCriterion("re_surl >=", value, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlLessThan(String value) {
            addCriterion("re_surl <", value, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlLessThanOrEqualTo(String value) {
            addCriterion("re_surl <=", value, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlLike(String value) {
            addCriterion("re_surl like", value, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlNotLike(String value) {
            addCriterion("re_surl not like", value, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlIn(List<String> values) {
            addCriterion("re_surl in", values, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlNotIn(List<String> values) {
            addCriterion("re_surl not in", values, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlBetween(String value1, String value2) {
            addCriterion("re_surl between", value1, value2, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReSurlNotBetween(String value1, String value2) {
            addCriterion("re_surl not between", value1, value2, "reSurl");
            return (Criteria) this;
        }

        public Criteria andReAddtimeIsNull() {
            addCriterion("re_addtime is null");
            return (Criteria) this;
        }

        public Criteria andReAddtimeIsNotNull() {
            addCriterion("re_addtime is not null");
            return (Criteria) this;
        }

        public Criteria andReAddtimeEqualTo(String value) {
            addCriterion("re_addtime =", value, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeNotEqualTo(String value) {
            addCriterion("re_addtime <>", value, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeGreaterThan(String value) {
            addCriterion("re_addtime >", value, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeGreaterThanOrEqualTo(String value) {
            addCriterion("re_addtime >=", value, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeLessThan(String value) {
            addCriterion("re_addtime <", value, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeLessThanOrEqualTo(String value) {
            addCriterion("re_addtime <=", value, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeLike(String value) {
            addCriterion("re_addtime like", value, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeNotLike(String value) {
            addCriterion("re_addtime not like", value, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeIn(List<String> values) {
            addCriterion("re_addtime in", values, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeNotIn(List<String> values) {
            addCriterion("re_addtime not in", values, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeBetween(String value1, String value2) {
            addCriterion("re_addtime between", value1, value2, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReAddtimeNotBetween(String value1, String value2) {
            addCriterion("re_addtime not between", value1, value2, "reAddtime");
            return (Criteria) this;
        }

        public Criteria andReItemIsNull() {
            addCriterion("re_item is null");
            return (Criteria) this;
        }

        public Criteria andReItemIsNotNull() {
            addCriterion("re_item is not null");
            return (Criteria) this;
        }

        public Criteria andReItemEqualTo(String value) {
            addCriterion("re_item =", value, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemNotEqualTo(String value) {
            addCriterion("re_item <>", value, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemGreaterThan(String value) {
            addCriterion("re_item >", value, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemGreaterThanOrEqualTo(String value) {
            addCriterion("re_item >=", value, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemLessThan(String value) {
            addCriterion("re_item <", value, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemLessThanOrEqualTo(String value) {
            addCriterion("re_item <=", value, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemLike(String value) {
            addCriterion("re_item like", value, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemNotLike(String value) {
            addCriterion("re_item not like", value, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemIn(List<String> values) {
            addCriterion("re_item in", values, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemNotIn(List<String> values) {
            addCriterion("re_item not in", values, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemBetween(String value1, String value2) {
            addCriterion("re_item between", value1, value2, "reItem");
            return (Criteria) this;
        }

        public Criteria andReItemNotBetween(String value1, String value2) {
            addCriterion("re_item not between", value1, value2, "reItem");
            return (Criteria) this;
        }

        public Criteria andReElementIsNull() {
            addCriterion("re_element is null");
            return (Criteria) this;
        }

        public Criteria andReElementIsNotNull() {
            addCriterion("re_element is not null");
            return (Criteria) this;
        }

        public Criteria andReElementEqualTo(String value) {
            addCriterion("re_element =", value, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementNotEqualTo(String value) {
            addCriterion("re_element <>", value, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementGreaterThan(String value) {
            addCriterion("re_element >", value, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementGreaterThanOrEqualTo(String value) {
            addCriterion("re_element >=", value, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementLessThan(String value) {
            addCriterion("re_element <", value, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementLessThanOrEqualTo(String value) {
            addCriterion("re_element <=", value, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementLike(String value) {
            addCriterion("re_element like", value, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementNotLike(String value) {
            addCriterion("re_element not like", value, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementIn(List<String> values) {
            addCriterion("re_element in", values, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementNotIn(List<String> values) {
            addCriterion("re_element not in", values, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementBetween(String value1, String value2) {
            addCriterion("re_element between", value1, value2, "reElement");
            return (Criteria) this;
        }

        public Criteria andReElementNotBetween(String value1, String value2) {
            addCriterion("re_element not between", value1, value2, "reElement");
            return (Criteria) this;
        }

        public Criteria andReTreeIsNull() {
            addCriterion("re_tree is null");
            return (Criteria) this;
        }

        public Criteria andReTreeIsNotNull() {
            addCriterion("re_tree is not null");
            return (Criteria) this;
        }

        public Criteria andReTreeEqualTo(String value) {
            addCriterion("re_tree =", value, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeNotEqualTo(String value) {
            addCriterion("re_tree <>", value, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeGreaterThan(String value) {
            addCriterion("re_tree >", value, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeGreaterThanOrEqualTo(String value) {
            addCriterion("re_tree >=", value, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeLessThan(String value) {
            addCriterion("re_tree <", value, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeLessThanOrEqualTo(String value) {
            addCriterion("re_tree <=", value, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeLike(String value) {
            addCriterion("re_tree like", value, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeNotLike(String value) {
            addCriterion("re_tree not like", value, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeIn(List<String> values) {
            addCriterion("re_tree in", values, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeNotIn(List<String> values) {
            addCriterion("re_tree not in", values, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeBetween(String value1, String value2) {
            addCriterion("re_tree between", value1, value2, "reTree");
            return (Criteria) this;
        }

        public Criteria andReTreeNotBetween(String value1, String value2) {
            addCriterion("re_tree not between", value1, value2, "reTree");
            return (Criteria) this;
        }

        public Criteria andReLimitIsNull() {
            addCriterion("re_limit is null");
            return (Criteria) this;
        }

        public Criteria andReLimitIsNotNull() {
            addCriterion("re_limit is not null");
            return (Criteria) this;
        }

        public Criteria andReLimitEqualTo(Integer value) {
            addCriterion("re_limit =", value, "reLimit");
            return (Criteria) this;
        }

        public Criteria andReLimitNotEqualTo(Integer value) {
            addCriterion("re_limit <>", value, "reLimit");
            return (Criteria) this;
        }

        public Criteria andReLimitGreaterThan(Integer value) {
            addCriterion("re_limit >", value, "reLimit");
            return (Criteria) this;
        }

        public Criteria andReLimitGreaterThanOrEqualTo(Integer value) {
            addCriterion("re_limit >=", value, "reLimit");
            return (Criteria) this;
        }

        public Criteria andReLimitLessThan(Integer value) {
            addCriterion("re_limit <", value, "reLimit");
            return (Criteria) this;
        }

        public Criteria andReLimitLessThanOrEqualTo(Integer value) {
            addCriterion("re_limit <=", value, "reLimit");
            return (Criteria) this;
        }

        public Criteria andReLimitIn(List<Integer> values) {
            addCriterion("re_limit in", values, "reLimit");
            return (Criteria) this;
        }

        public Criteria andReLimitNotIn(List<Integer> values) {
            addCriterion("re_limit not in", values, "reLimit");
            return (Criteria) this;
        }

        public Criteria andReLimitBetween(Integer value1, Integer value2) {
            addCriterion("re_limit between", value1, value2, "reLimit");
            return (Criteria) this;
        }

        public Criteria andReLimitNotBetween(Integer value1, Integer value2) {
            addCriterion("re_limit not between", value1, value2, "reLimit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detection
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table detection
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}