package com.datacenter.bean;

import java.util.ArrayList;
import java.util.List;

public class GeturlExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geturl
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geturl
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table geturl
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public GeturlExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geturl
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUrlIdIsNull() {
            addCriterion("url_id is null");
            return (Criteria) this;
        }

        public Criteria andUrlIdIsNotNull() {
            addCriterion("url_id is not null");
            return (Criteria) this;
        }

        public Criteria andUrlIdEqualTo(Integer value) {
            addCriterion("url_id =", value, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlIdNotEqualTo(Integer value) {
            addCriterion("url_id <>", value, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlIdGreaterThan(Integer value) {
            addCriterion("url_id >", value, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("url_id >=", value, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlIdLessThan(Integer value) {
            addCriterion("url_id <", value, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlIdLessThanOrEqualTo(Integer value) {
            addCriterion("url_id <=", value, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlIdIn(List<Integer> values) {
            addCriterion("url_id in", values, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlIdNotIn(List<Integer> values) {
            addCriterion("url_id not in", values, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlIdBetween(Integer value1, Integer value2) {
            addCriterion("url_id between", value1, value2, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlIdNotBetween(Integer value1, Integer value2) {
            addCriterion("url_id not between", value1, value2, "urlId");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameIsNull() {
            addCriterion("url_getname is null");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameIsNotNull() {
            addCriterion("url_getname is not null");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameEqualTo(String value) {
            addCriterion("url_getname =", value, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameNotEqualTo(String value) {
            addCriterion("url_getname <>", value, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameGreaterThan(String value) {
            addCriterion("url_getname >", value, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameGreaterThanOrEqualTo(String value) {
            addCriterion("url_getname >=", value, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameLessThan(String value) {
            addCriterion("url_getname <", value, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameLessThanOrEqualTo(String value) {
            addCriterion("url_getname <=", value, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameLike(String value) {
            addCriterion("url_getname like", value, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameNotLike(String value) {
            addCriterion("url_getname not like", value, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameIn(List<String> values) {
            addCriterion("url_getname in", values, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameNotIn(List<String> values) {
            addCriterion("url_getname not in", values, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameBetween(String value1, String value2) {
            addCriterion("url_getname between", value1, value2, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGetnameNotBetween(String value1, String value2) {
            addCriterion("url_getname not between", value1, value2, "urlGetname");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeIsNull() {
            addCriterion("url_gettime is null");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeIsNotNull() {
            addCriterion("url_gettime is not null");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeEqualTo(String value) {
            addCriterion("url_gettime =", value, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeNotEqualTo(String value) {
            addCriterion("url_gettime <>", value, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeGreaterThan(String value) {
            addCriterion("url_gettime >", value, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeGreaterThanOrEqualTo(String value) {
            addCriterion("url_gettime >=", value, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeLessThan(String value) {
            addCriterion("url_gettime <", value, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeLessThanOrEqualTo(String value) {
            addCriterion("url_gettime <=", value, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeLike(String value) {
            addCriterion("url_gettime like", value, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeNotLike(String value) {
            addCriterion("url_gettime not like", value, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeIn(List<String> values) {
            addCriterion("url_gettime in", values, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeNotIn(List<String> values) {
            addCriterion("url_gettime not in", values, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeBetween(String value1, String value2) {
            addCriterion("url_gettime between", value1, value2, "urlGettime");
            return (Criteria) this;
        }

        public Criteria andUrlGettimeNotBetween(String value1, String value2) {
            addCriterion("url_gettime not between", value1, value2, "urlGettime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geturl
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table geturl
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}