package com.datacenter.bean;

public class News {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_id
     *
     * @mbggenerated
     */
    private Integer newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_url
     *
     * @mbggenerated
     */
    private String newsUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_title
     *
     * @mbggenerated
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_type
     *
     * @mbggenerated
     */
    private String newsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_modal
     *
     * @mbggenerated
     */
    private String newsModal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_belong
     *
     * @mbggenerated
     */
    private String newsBelong;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_accessible
     *
     * @mbggenerated
     */
    private String newsAccessible;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_data
     *
     * @mbggenerated
     */
    private String newsData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_time
     *
     * @mbggenerated
     */
    private String newsTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_storage
     *
     * @mbggenerated
     */
    private String newsStorage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_downtime
     *
     * @mbggenerated
     */
    private String newsDowntime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_remarktwo
     *
     * @mbggenerated
     */
    private String newsRemarktwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_detail
     *
     * @mbggenerated
     */
    private String newsDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_id
     *
     * @return the value of news.news_id
     *
     * @mbggenerated
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_id
     *
     * @param newsId the value for news.news_id
     *
     * @mbggenerated
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_url
     *
     * @return the value of news.news_url
     *
     * @mbggenerated
     */
    public String getNewsUrl() {
        return newsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_url
     *
     * @param newsUrl the value for news.news_url
     *
     * @mbggenerated
     */
    public void setNewsUrl(String newsUrl) {
        this.newsUrl = newsUrl == null ? null : newsUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_title
     *
     * @return the value of news.news_title
     *
     * @mbggenerated
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_title
     *
     * @param newsTitle the value for news.news_title
     *
     * @mbggenerated
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_type
     *
     * @return the value of news.news_type
     *
     * @mbggenerated
     */
    public String getNewsType() {
        return newsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_type
     *
     * @param newsType the value for news.news_type
     *
     * @mbggenerated
     */
    public void setNewsType(String newsType) {
        this.newsType = newsType == null ? null : newsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_modal
     *
     * @return the value of news.news_modal
     *
     * @mbggenerated
     */
    public String getNewsModal() {
        return newsModal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_modal
     *
     * @param newsModal the value for news.news_modal
     *
     * @mbggenerated
     */
    public void setNewsModal(String newsModal) {
        this.newsModal = newsModal == null ? null : newsModal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_belong
     *
     * @return the value of news.news_belong
     *
     * @mbggenerated
     */
    public String getNewsBelong() {
        return newsBelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_belong
     *
     * @param newsBelong the value for news.news_belong
     *
     * @mbggenerated
     */
    public void setNewsBelong(String newsBelong) {
        this.newsBelong = newsBelong == null ? null : newsBelong.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_accessible
     *
     * @return the value of news.news_accessible
     *
     * @mbggenerated
     */
    public String getNewsAccessible() {
        return newsAccessible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_accessible
     *
     * @param newsAccessible the value for news.news_accessible
     *
     * @mbggenerated
     */
    public void setNewsAccessible(String newsAccessible) {
        this.newsAccessible = newsAccessible == null ? null : newsAccessible.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_data
     *
     * @return the value of news.news_data
     *
     * @mbggenerated
     */
    public String getNewsData() {
        return newsData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_data
     *
     * @param newsData the value for news.news_data
     *
     * @mbggenerated
     */
    public void setNewsData(String newsData) {
        this.newsData = newsData == null ? null : newsData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_time
     *
     * @return the value of news.news_time
     *
     * @mbggenerated
     */
    public String getNewsTime() {
        return newsTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_time
     *
     * @param newsTime the value for news.news_time
     *
     * @mbggenerated
     */
    public void setNewsTime(String newsTime) {
        this.newsTime = newsTime == null ? null : newsTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_storage
     *
     * @return the value of news.news_storage
     *
     * @mbggenerated
     */
    public String getNewsStorage() {
        return newsStorage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_storage
     *
     * @param newsStorage the value for news.news_storage
     *
     * @mbggenerated
     */
    public void setNewsStorage(String newsStorage) {
        this.newsStorage = newsStorage == null ? null : newsStorage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_downtime
     *
     * @return the value of news.news_downtime
     *
     * @mbggenerated
     */
    public String getNewsDowntime() {
        return newsDowntime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_downtime
     *
     * @param newsDowntime the value for news.news_downtime
     *
     * @mbggenerated
     */
    public void setNewsDowntime(String newsDowntime) {
        this.newsDowntime = newsDowntime == null ? null : newsDowntime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_remarktwo
     *
     * @return the value of news.news_remarktwo
     *
     * @mbggenerated
     */
    public String getNewsRemarktwo() {
        return newsRemarktwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_remarktwo
     *
     * @param newsRemarktwo the value for news.news_remarktwo
     *
     * @mbggenerated
     */
    public void setNewsRemarktwo(String newsRemarktwo) {
        this.newsRemarktwo = newsRemarktwo == null ? null : newsRemarktwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_detail
     *
     * @return the value of news.news_detail
     *
     * @mbggenerated
     */
    public String getNewsDetail() {
        return newsDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_detail
     *
     * @param newsDetail the value for news.news_detail
     *
     * @mbggenerated
     */
    public void setNewsDetail(String newsDetail) {
        this.newsDetail = newsDetail == null ? null : newsDetail.trim();
    }
}