package com.datacenter.bean;

import java.util.ArrayList;
import java.util.List;

public class NewsallExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newsall
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newsall
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table newsall
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public NewsallExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newsall
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNewsIdIsNull() {
            addCriterion("news_id is null");
            return (Criteria) this;
        }

        public Criteria andNewsIdIsNotNull() {
            addCriterion("news_id is not null");
            return (Criteria) this;
        }

        public Criteria andNewsIdEqualTo(Integer value) {
            addCriterion("news_id =", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdNotEqualTo(Integer value) {
            addCriterion("news_id <>", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdGreaterThan(Integer value) {
            addCriterion("news_id >", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("news_id >=", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdLessThan(Integer value) {
            addCriterion("news_id <", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdLessThanOrEqualTo(Integer value) {
            addCriterion("news_id <=", value, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdIn(List<Integer> values) {
            addCriterion("news_id in", values, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdNotIn(List<Integer> values) {
            addCriterion("news_id not in", values, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdBetween(Integer value1, Integer value2) {
            addCriterion("news_id between", value1, value2, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("news_id not between", value1, value2, "newsId");
            return (Criteria) this;
        }

        public Criteria andNewsUrlIsNull() {
            addCriterion("news_url is null");
            return (Criteria) this;
        }

        public Criteria andNewsUrlIsNotNull() {
            addCriterion("news_url is not null");
            return (Criteria) this;
        }

        public Criteria andNewsUrlEqualTo(String value) {
            addCriterion("news_url =", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlNotEqualTo(String value) {
            addCriterion("news_url <>", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlGreaterThan(String value) {
            addCriterion("news_url >", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlGreaterThanOrEqualTo(String value) {
            addCriterion("news_url >=", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlLessThan(String value) {
            addCriterion("news_url <", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlLessThanOrEqualTo(String value) {
            addCriterion("news_url <=", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlLike(String value) {
            addCriterion("news_url like", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlNotLike(String value) {
            addCriterion("news_url not like", value, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlIn(List<String> values) {
            addCriterion("news_url in", values, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlNotIn(List<String> values) {
            addCriterion("news_url not in", values, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlBetween(String value1, String value2) {
            addCriterion("news_url between", value1, value2, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsUrlNotBetween(String value1, String value2) {
            addCriterion("news_url not between", value1, value2, "newsUrl");
            return (Criteria) this;
        }

        public Criteria andNewsTitleIsNull() {
            addCriterion("news_title is null");
            return (Criteria) this;
        }

        public Criteria andNewsTitleIsNotNull() {
            addCriterion("news_title is not null");
            return (Criteria) this;
        }

        public Criteria andNewsTitleEqualTo(String value) {
            addCriterion("news_title =", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotEqualTo(String value) {
            addCriterion("news_title <>", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleGreaterThan(String value) {
            addCriterion("news_title >", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleGreaterThanOrEqualTo(String value) {
            addCriterion("news_title >=", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleLessThan(String value) {
            addCriterion("news_title <", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleLessThanOrEqualTo(String value) {
            addCriterion("news_title <=", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleLike(String value) {
            addCriterion("news_title like", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotLike(String value) {
            addCriterion("news_title not like", value, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleIn(List<String> values) {
            addCriterion("news_title in", values, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotIn(List<String> values) {
            addCriterion("news_title not in", values, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleBetween(String value1, String value2) {
            addCriterion("news_title between", value1, value2, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTitleNotBetween(String value1, String value2) {
            addCriterion("news_title not between", value1, value2, "newsTitle");
            return (Criteria) this;
        }

        public Criteria andNewsTypeIsNull() {
            addCriterion("news_type is null");
            return (Criteria) this;
        }

        public Criteria andNewsTypeIsNotNull() {
            addCriterion("news_type is not null");
            return (Criteria) this;
        }

        public Criteria andNewsTypeEqualTo(String value) {
            addCriterion("news_type =", value, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeNotEqualTo(String value) {
            addCriterion("news_type <>", value, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeGreaterThan(String value) {
            addCriterion("news_type >", value, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeGreaterThanOrEqualTo(String value) {
            addCriterion("news_type >=", value, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeLessThan(String value) {
            addCriterion("news_type <", value, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeLessThanOrEqualTo(String value) {
            addCriterion("news_type <=", value, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeLike(String value) {
            addCriterion("news_type like", value, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeNotLike(String value) {
            addCriterion("news_type not like", value, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeIn(List<String> values) {
            addCriterion("news_type in", values, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeNotIn(List<String> values) {
            addCriterion("news_type not in", values, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeBetween(String value1, String value2) {
            addCriterion("news_type between", value1, value2, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsTypeNotBetween(String value1, String value2) {
            addCriterion("news_type not between", value1, value2, "newsType");
            return (Criteria) this;
        }

        public Criteria andNewsModalIsNull() {
            addCriterion("news_modal is null");
            return (Criteria) this;
        }

        public Criteria andNewsModalIsNotNull() {
            addCriterion("news_modal is not null");
            return (Criteria) this;
        }

        public Criteria andNewsModalEqualTo(String value) {
            addCriterion("news_modal =", value, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalNotEqualTo(String value) {
            addCriterion("news_modal <>", value, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalGreaterThan(String value) {
            addCriterion("news_modal >", value, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalGreaterThanOrEqualTo(String value) {
            addCriterion("news_modal >=", value, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalLessThan(String value) {
            addCriterion("news_modal <", value, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalLessThanOrEqualTo(String value) {
            addCriterion("news_modal <=", value, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalLike(String value) {
            addCriterion("news_modal like", value, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalNotLike(String value) {
            addCriterion("news_modal not like", value, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalIn(List<String> values) {
            addCriterion("news_modal in", values, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalNotIn(List<String> values) {
            addCriterion("news_modal not in", values, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalBetween(String value1, String value2) {
            addCriterion("news_modal between", value1, value2, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsModalNotBetween(String value1, String value2) {
            addCriterion("news_modal not between", value1, value2, "newsModal");
            return (Criteria) this;
        }

        public Criteria andNewsBelongIsNull() {
            addCriterion("news_belong is null");
            return (Criteria) this;
        }

        public Criteria andNewsBelongIsNotNull() {
            addCriterion("news_belong is not null");
            return (Criteria) this;
        }

        public Criteria andNewsBelongEqualTo(String value) {
            addCriterion("news_belong =", value, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongNotEqualTo(String value) {
            addCriterion("news_belong <>", value, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongGreaterThan(String value) {
            addCriterion("news_belong >", value, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongGreaterThanOrEqualTo(String value) {
            addCriterion("news_belong >=", value, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongLessThan(String value) {
            addCriterion("news_belong <", value, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongLessThanOrEqualTo(String value) {
            addCriterion("news_belong <=", value, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongLike(String value) {
            addCriterion("news_belong like", value, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongNotLike(String value) {
            addCriterion("news_belong not like", value, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongIn(List<String> values) {
            addCriterion("news_belong in", values, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongNotIn(List<String> values) {
            addCriterion("news_belong not in", values, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongBetween(String value1, String value2) {
            addCriterion("news_belong between", value1, value2, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsBelongNotBetween(String value1, String value2) {
            addCriterion("news_belong not between", value1, value2, "newsBelong");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleIsNull() {
            addCriterion("news_accessible is null");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleIsNotNull() {
            addCriterion("news_accessible is not null");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleEqualTo(String value) {
            addCriterion("news_accessible =", value, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleNotEqualTo(String value) {
            addCriterion("news_accessible <>", value, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleGreaterThan(String value) {
            addCriterion("news_accessible >", value, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleGreaterThanOrEqualTo(String value) {
            addCriterion("news_accessible >=", value, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleLessThan(String value) {
            addCriterion("news_accessible <", value, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleLessThanOrEqualTo(String value) {
            addCriterion("news_accessible <=", value, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleLike(String value) {
            addCriterion("news_accessible like", value, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleNotLike(String value) {
            addCriterion("news_accessible not like", value, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleIn(List<String> values) {
            addCriterion("news_accessible in", values, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleNotIn(List<String> values) {
            addCriterion("news_accessible not in", values, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleBetween(String value1, String value2) {
            addCriterion("news_accessible between", value1, value2, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsAccessibleNotBetween(String value1, String value2) {
            addCriterion("news_accessible not between", value1, value2, "newsAccessible");
            return (Criteria) this;
        }

        public Criteria andNewsDataIsNull() {
            addCriterion("news_data is null");
            return (Criteria) this;
        }

        public Criteria andNewsDataIsNotNull() {
            addCriterion("news_data is not null");
            return (Criteria) this;
        }

        public Criteria andNewsDataEqualTo(String value) {
            addCriterion("news_data =", value, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataNotEqualTo(String value) {
            addCriterion("news_data <>", value, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataGreaterThan(String value) {
            addCriterion("news_data >", value, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataGreaterThanOrEqualTo(String value) {
            addCriterion("news_data >=", value, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataLessThan(String value) {
            addCriterion("news_data <", value, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataLessThanOrEqualTo(String value) {
            addCriterion("news_data <=", value, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataLike(String value) {
            addCriterion("news_data like", value, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataNotLike(String value) {
            addCriterion("news_data not like", value, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataIn(List<String> values) {
            addCriterion("news_data in", values, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataNotIn(List<String> values) {
            addCriterion("news_data not in", values, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataBetween(String value1, String value2) {
            addCriterion("news_data between", value1, value2, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsDataNotBetween(String value1, String value2) {
            addCriterion("news_data not between", value1, value2, "newsData");
            return (Criteria) this;
        }

        public Criteria andNewsTimeIsNull() {
            addCriterion("news_time is null");
            return (Criteria) this;
        }

        public Criteria andNewsTimeIsNotNull() {
            addCriterion("news_time is not null");
            return (Criteria) this;
        }

        public Criteria andNewsTimeEqualTo(String value) {
            addCriterion("news_time =", value, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeNotEqualTo(String value) {
            addCriterion("news_time <>", value, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeGreaterThan(String value) {
            addCriterion("news_time >", value, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeGreaterThanOrEqualTo(String value) {
            addCriterion("news_time >=", value, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeLessThan(String value) {
            addCriterion("news_time <", value, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeLessThanOrEqualTo(String value) {
            addCriterion("news_time <=", value, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeLike(String value) {
            addCriterion("news_time like", value, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeNotLike(String value) {
            addCriterion("news_time not like", value, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeIn(List<String> values) {
            addCriterion("news_time in", values, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeNotIn(List<String> values) {
            addCriterion("news_time not in", values, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeBetween(String value1, String value2) {
            addCriterion("news_time between", value1, value2, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsTimeNotBetween(String value1, String value2) {
            addCriterion("news_time not between", value1, value2, "newsTime");
            return (Criteria) this;
        }

        public Criteria andNewsStorageIsNull() {
            addCriterion("news_storage is null");
            return (Criteria) this;
        }

        public Criteria andNewsStorageIsNotNull() {
            addCriterion("news_storage is not null");
            return (Criteria) this;
        }

        public Criteria andNewsStorageEqualTo(String value) {
            addCriterion("news_storage =", value, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageNotEqualTo(String value) {
            addCriterion("news_storage <>", value, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageGreaterThan(String value) {
            addCriterion("news_storage >", value, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageGreaterThanOrEqualTo(String value) {
            addCriterion("news_storage >=", value, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageLessThan(String value) {
            addCriterion("news_storage <", value, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageLessThanOrEqualTo(String value) {
            addCriterion("news_storage <=", value, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageLike(String value) {
            addCriterion("news_storage like", value, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageNotLike(String value) {
            addCriterion("news_storage not like", value, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageIn(List<String> values) {
            addCriterion("news_storage in", values, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageNotIn(List<String> values) {
            addCriterion("news_storage not in", values, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageBetween(String value1, String value2) {
            addCriterion("news_storage between", value1, value2, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsStorageNotBetween(String value1, String value2) {
            addCriterion("news_storage not between", value1, value2, "newsStorage");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeIsNull() {
            addCriterion("news_downtime is null");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeIsNotNull() {
            addCriterion("news_downtime is not null");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeEqualTo(String value) {
            addCriterion("news_downtime =", value, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeNotEqualTo(String value) {
            addCriterion("news_downtime <>", value, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeGreaterThan(String value) {
            addCriterion("news_downtime >", value, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeGreaterThanOrEqualTo(String value) {
            addCriterion("news_downtime >=", value, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeLessThan(String value) {
            addCriterion("news_downtime <", value, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeLessThanOrEqualTo(String value) {
            addCriterion("news_downtime <=", value, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeLike(String value) {
            addCriterion("news_downtime like", value, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeNotLike(String value) {
            addCriterion("news_downtime not like", value, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeIn(List<String> values) {
            addCriterion("news_downtime in", values, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeNotIn(List<String> values) {
            addCriterion("news_downtime not in", values, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeBetween(String value1, String value2) {
            addCriterion("news_downtime between", value1, value2, "newsDowntime");
            return (Criteria) this;
        }

        public Criteria andNewsDowntimeNotBetween(String value1, String value2) {
            addCriterion("news_downtime not between", value1, value2, "newsDowntime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newsall
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table newsall
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}