package com.datacenter.bean;

public class Sampling {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_id
     *
     * @mbggenerated
     */
    private Integer saId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_url
     *
     * @mbggenerated
     */
    private String saUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_surl
     *
     * @mbggenerated
     */
    private String saSurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_item
     *
     * @mbggenerated
     */
    private String saItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_element
     *
     * @mbggenerated
     */
    private String saElement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_state
     *
     * @mbggenerated
     */
    private Integer saState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_startime
     *
     * @mbggenerated
     */
    private String saStartime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_stotime
     *
     * @mbggenerated
     */
    private String saStotime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_week
     *
     * @mbggenerated
     */
    private Integer saWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sampling.sa_day
     *
     * @mbggenerated
     */
    private Integer saDay;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_id
     *
     * @return the value of sampling.sa_id
     *
     * @mbggenerated
     */
    public Integer getSaId() {
        return saId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_id
     *
     * @param saId the value for sampling.sa_id
     *
     * @mbggenerated
     */
    public void setSaId(Integer saId) {
        this.saId = saId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_url
     *
     * @return the value of sampling.sa_url
     *
     * @mbggenerated
     */
    public String getSaUrl() {
        return saUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_url
     *
     * @param saUrl the value for sampling.sa_url
     *
     * @mbggenerated
     */
    public void setSaUrl(String saUrl) {
        this.saUrl = saUrl == null ? null : saUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_surl
     *
     * @return the value of sampling.sa_surl
     *
     * @mbggenerated
     */
    public String getSaSurl() {
        return saSurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_surl
     *
     * @param saSurl the value for sampling.sa_surl
     *
     * @mbggenerated
     */
    public void setSaSurl(String saSurl) {
        this.saSurl = saSurl == null ? null : saSurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_item
     *
     * @return the value of sampling.sa_item
     *
     * @mbggenerated
     */
    public String getSaItem() {
        return saItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_item
     *
     * @param saItem the value for sampling.sa_item
     *
     * @mbggenerated
     */
    public void setSaItem(String saItem) {
        this.saItem = saItem == null ? null : saItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_element
     *
     * @return the value of sampling.sa_element
     *
     * @mbggenerated
     */
    public String getSaElement() {
        return saElement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_element
     *
     * @param saElement the value for sampling.sa_element
     *
     * @mbggenerated
     */
    public void setSaElement(String saElement) {
        this.saElement = saElement == null ? null : saElement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_state
     *
     * @return the value of sampling.sa_state
     *
     * @mbggenerated
     */
    public Integer getSaState() {
        return saState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_state
     *
     * @param saState the value for sampling.sa_state
     *
     * @mbggenerated
     */
    public void setSaState(Integer saState) {
        this.saState = saState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_startime
     *
     * @return the value of sampling.sa_startime
     *
     * @mbggenerated
     */
    public String getSaStartime() {
        return saStartime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_startime
     *
     * @param saStartime the value for sampling.sa_startime
     *
     * @mbggenerated
     */
    public void setSaStartime(String saStartime) {
        this.saStartime = saStartime == null ? null : saStartime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_stotime
     *
     * @return the value of sampling.sa_stotime
     *
     * @mbggenerated
     */
    public String getSaStotime() {
        return saStotime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_stotime
     *
     * @param saStotime the value for sampling.sa_stotime
     *
     * @mbggenerated
     */
    public void setSaStotime(String saStotime) {
        this.saStotime = saStotime == null ? null : saStotime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_week
     *
     * @return the value of sampling.sa_week
     *
     * @mbggenerated
     */
    public Integer getSaWeek() {
        return saWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_week
     *
     * @param saWeek the value for sampling.sa_week
     *
     * @mbggenerated
     */
    public void setSaWeek(Integer saWeek) {
        this.saWeek = saWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sampling.sa_day
     *
     * @return the value of sampling.sa_day
     *
     * @mbggenerated
     */
    public Integer getSaDay() {
        return saDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sampling.sa_day
     *
     * @param saDay the value for sampling.sa_day
     *
     * @mbggenerated
     */
    public void setSaDay(Integer saDay) {
        this.saDay = saDay;
    }
}