package com.datacenter.bean;

import java.util.ArrayList;
import java.util.List;

public class SamplingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sampling
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sampling
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sampling
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public SamplingExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sampling
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSaIdIsNull() {
            addCriterion("sa_id is null");
            return (Criteria) this;
        }

        public Criteria andSaIdIsNotNull() {
            addCriterion("sa_id is not null");
            return (Criteria) this;
        }

        public Criteria andSaIdEqualTo(Integer value) {
            addCriterion("sa_id =", value, "saId");
            return (Criteria) this;
        }

        public Criteria andSaIdNotEqualTo(Integer value) {
            addCriterion("sa_id <>", value, "saId");
            return (Criteria) this;
        }

        public Criteria andSaIdGreaterThan(Integer value) {
            addCriterion("sa_id >", value, "saId");
            return (Criteria) this;
        }

        public Criteria andSaIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sa_id >=", value, "saId");
            return (Criteria) this;
        }

        public Criteria andSaIdLessThan(Integer value) {
            addCriterion("sa_id <", value, "saId");
            return (Criteria) this;
        }

        public Criteria andSaIdLessThanOrEqualTo(Integer value) {
            addCriterion("sa_id <=", value, "saId");
            return (Criteria) this;
        }

        public Criteria andSaIdIn(List<Integer> values) {
            addCriterion("sa_id in", values, "saId");
            return (Criteria) this;
        }

        public Criteria andSaIdNotIn(List<Integer> values) {
            addCriterion("sa_id not in", values, "saId");
            return (Criteria) this;
        }

        public Criteria andSaIdBetween(Integer value1, Integer value2) {
            addCriterion("sa_id between", value1, value2, "saId");
            return (Criteria) this;
        }

        public Criteria andSaIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sa_id not between", value1, value2, "saId");
            return (Criteria) this;
        }

        public Criteria andSaUrlIsNull() {
            addCriterion("sa_url is null");
            return (Criteria) this;
        }

        public Criteria andSaUrlIsNotNull() {
            addCriterion("sa_url is not null");
            return (Criteria) this;
        }

        public Criteria andSaUrlEqualTo(String value) {
            addCriterion("sa_url =", value, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlNotEqualTo(String value) {
            addCriterion("sa_url <>", value, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlGreaterThan(String value) {
            addCriterion("sa_url >", value, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlGreaterThanOrEqualTo(String value) {
            addCriterion("sa_url >=", value, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlLessThan(String value) {
            addCriterion("sa_url <", value, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlLessThanOrEqualTo(String value) {
            addCriterion("sa_url <=", value, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlLike(String value) {
            addCriterion("sa_url like", value, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlNotLike(String value) {
            addCriterion("sa_url not like", value, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlIn(List<String> values) {
            addCriterion("sa_url in", values, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlNotIn(List<String> values) {
            addCriterion("sa_url not in", values, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlBetween(String value1, String value2) {
            addCriterion("sa_url between", value1, value2, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaUrlNotBetween(String value1, String value2) {
            addCriterion("sa_url not between", value1, value2, "saUrl");
            return (Criteria) this;
        }

        public Criteria andSaSurlIsNull() {
            addCriterion("sa_surl is null");
            return (Criteria) this;
        }

        public Criteria andSaSurlIsNotNull() {
            addCriterion("sa_surl is not null");
            return (Criteria) this;
        }

        public Criteria andSaSurlEqualTo(String value) {
            addCriterion("sa_surl =", value, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlNotEqualTo(String value) {
            addCriterion("sa_surl <>", value, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlGreaterThan(String value) {
            addCriterion("sa_surl >", value, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlGreaterThanOrEqualTo(String value) {
            addCriterion("sa_surl >=", value, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlLessThan(String value) {
            addCriterion("sa_surl <", value, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlLessThanOrEqualTo(String value) {
            addCriterion("sa_surl <=", value, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlLike(String value) {
            addCriterion("sa_surl like", value, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlNotLike(String value) {
            addCriterion("sa_surl not like", value, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlIn(List<String> values) {
            addCriterion("sa_surl in", values, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlNotIn(List<String> values) {
            addCriterion("sa_surl not in", values, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlBetween(String value1, String value2) {
            addCriterion("sa_surl between", value1, value2, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaSurlNotBetween(String value1, String value2) {
            addCriterion("sa_surl not between", value1, value2, "saSurl");
            return (Criteria) this;
        }

        public Criteria andSaItemIsNull() {
            addCriterion("sa_item is null");
            return (Criteria) this;
        }

        public Criteria andSaItemIsNotNull() {
            addCriterion("sa_item is not null");
            return (Criteria) this;
        }

        public Criteria andSaItemEqualTo(String value) {
            addCriterion("sa_item =", value, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemNotEqualTo(String value) {
            addCriterion("sa_item <>", value, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemGreaterThan(String value) {
            addCriterion("sa_item >", value, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemGreaterThanOrEqualTo(String value) {
            addCriterion("sa_item >=", value, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemLessThan(String value) {
            addCriterion("sa_item <", value, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemLessThanOrEqualTo(String value) {
            addCriterion("sa_item <=", value, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemLike(String value) {
            addCriterion("sa_item like", value, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemNotLike(String value) {
            addCriterion("sa_item not like", value, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemIn(List<String> values) {
            addCriterion("sa_item in", values, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemNotIn(List<String> values) {
            addCriterion("sa_item not in", values, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemBetween(String value1, String value2) {
            addCriterion("sa_item between", value1, value2, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaItemNotBetween(String value1, String value2) {
            addCriterion("sa_item not between", value1, value2, "saItem");
            return (Criteria) this;
        }

        public Criteria andSaElementIsNull() {
            addCriterion("sa_element is null");
            return (Criteria) this;
        }

        public Criteria andSaElementIsNotNull() {
            addCriterion("sa_element is not null");
            return (Criteria) this;
        }

        public Criteria andSaElementEqualTo(String value) {
            addCriterion("sa_element =", value, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementNotEqualTo(String value) {
            addCriterion("sa_element <>", value, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementGreaterThan(String value) {
            addCriterion("sa_element >", value, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementGreaterThanOrEqualTo(String value) {
            addCriterion("sa_element >=", value, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementLessThan(String value) {
            addCriterion("sa_element <", value, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementLessThanOrEqualTo(String value) {
            addCriterion("sa_element <=", value, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementLike(String value) {
            addCriterion("sa_element like", value, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementNotLike(String value) {
            addCriterion("sa_element not like", value, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementIn(List<String> values) {
            addCriterion("sa_element in", values, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementNotIn(List<String> values) {
            addCriterion("sa_element not in", values, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementBetween(String value1, String value2) {
            addCriterion("sa_element between", value1, value2, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaElementNotBetween(String value1, String value2) {
            addCriterion("sa_element not between", value1, value2, "saElement");
            return (Criteria) this;
        }

        public Criteria andSaStateIsNull() {
            addCriterion("sa_state is null");
            return (Criteria) this;
        }

        public Criteria andSaStateIsNotNull() {
            addCriterion("sa_state is not null");
            return (Criteria) this;
        }

        public Criteria andSaStateEqualTo(Integer value) {
            addCriterion("sa_state =", value, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStateNotEqualTo(Integer value) {
            addCriterion("sa_state <>", value, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStateGreaterThan(Integer value) {
            addCriterion("sa_state >", value, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("sa_state >=", value, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStateLessThan(Integer value) {
            addCriterion("sa_state <", value, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStateLessThanOrEqualTo(Integer value) {
            addCriterion("sa_state <=", value, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStateIn(List<Integer> values) {
            addCriterion("sa_state in", values, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStateNotIn(List<Integer> values) {
            addCriterion("sa_state not in", values, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStateBetween(Integer value1, Integer value2) {
            addCriterion("sa_state between", value1, value2, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStateNotBetween(Integer value1, Integer value2) {
            addCriterion("sa_state not between", value1, value2, "saState");
            return (Criteria) this;
        }

        public Criteria andSaStartimeIsNull() {
            addCriterion("sa_startime is null");
            return (Criteria) this;
        }

        public Criteria andSaStartimeIsNotNull() {
            addCriterion("sa_startime is not null");
            return (Criteria) this;
        }

        public Criteria andSaStartimeEqualTo(String value) {
            addCriterion("sa_startime =", value, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeNotEqualTo(String value) {
            addCriterion("sa_startime <>", value, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeGreaterThan(String value) {
            addCriterion("sa_startime >", value, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeGreaterThanOrEqualTo(String value) {
            addCriterion("sa_startime >=", value, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeLessThan(String value) {
            addCriterion("sa_startime <", value, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeLessThanOrEqualTo(String value) {
            addCriterion("sa_startime <=", value, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeLike(String value) {
            addCriterion("sa_startime like", value, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeNotLike(String value) {
            addCriterion("sa_startime not like", value, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeIn(List<String> values) {
            addCriterion("sa_startime in", values, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeNotIn(List<String> values) {
            addCriterion("sa_startime not in", values, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeBetween(String value1, String value2) {
            addCriterion("sa_startime between", value1, value2, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStartimeNotBetween(String value1, String value2) {
            addCriterion("sa_startime not between", value1, value2, "saStartime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeIsNull() {
            addCriterion("sa_stotime is null");
            return (Criteria) this;
        }

        public Criteria andSaStotimeIsNotNull() {
            addCriterion("sa_stotime is not null");
            return (Criteria) this;
        }

        public Criteria andSaStotimeEqualTo(String value) {
            addCriterion("sa_stotime =", value, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeNotEqualTo(String value) {
            addCriterion("sa_stotime <>", value, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeGreaterThan(String value) {
            addCriterion("sa_stotime >", value, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeGreaterThanOrEqualTo(String value) {
            addCriterion("sa_stotime >=", value, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeLessThan(String value) {
            addCriterion("sa_stotime <", value, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeLessThanOrEqualTo(String value) {
            addCriterion("sa_stotime <=", value, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeLike(String value) {
            addCriterion("sa_stotime like", value, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeNotLike(String value) {
            addCriterion("sa_stotime not like", value, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeIn(List<String> values) {
            addCriterion("sa_stotime in", values, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeNotIn(List<String> values) {
            addCriterion("sa_stotime not in", values, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeBetween(String value1, String value2) {
            addCriterion("sa_stotime between", value1, value2, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaStotimeNotBetween(String value1, String value2) {
            addCriterion("sa_stotime not between", value1, value2, "saStotime");
            return (Criteria) this;
        }

        public Criteria andSaWeekIsNull() {
            addCriterion("sa_week is null");
            return (Criteria) this;
        }

        public Criteria andSaWeekIsNotNull() {
            addCriterion("sa_week is not null");
            return (Criteria) this;
        }

        public Criteria andSaWeekEqualTo(Integer value) {
            addCriterion("sa_week =", value, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaWeekNotEqualTo(Integer value) {
            addCriterion("sa_week <>", value, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaWeekGreaterThan(Integer value) {
            addCriterion("sa_week >", value, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaWeekGreaterThanOrEqualTo(Integer value) {
            addCriterion("sa_week >=", value, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaWeekLessThan(Integer value) {
            addCriterion("sa_week <", value, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaWeekLessThanOrEqualTo(Integer value) {
            addCriterion("sa_week <=", value, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaWeekIn(List<Integer> values) {
            addCriterion("sa_week in", values, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaWeekNotIn(List<Integer> values) {
            addCriterion("sa_week not in", values, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaWeekBetween(Integer value1, Integer value2) {
            addCriterion("sa_week between", value1, value2, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaWeekNotBetween(Integer value1, Integer value2) {
            addCriterion("sa_week not between", value1, value2, "saWeek");
            return (Criteria) this;
        }

        public Criteria andSaDayIsNull() {
            addCriterion("sa_day is null");
            return (Criteria) this;
        }

        public Criteria andSaDayIsNotNull() {
            addCriterion("sa_day is not null");
            return (Criteria) this;
        }

        public Criteria andSaDayEqualTo(Integer value) {
            addCriterion("sa_day =", value, "saDay");
            return (Criteria) this;
        }

        public Criteria andSaDayNotEqualTo(Integer value) {
            addCriterion("sa_day <>", value, "saDay");
            return (Criteria) this;
        }

        public Criteria andSaDayGreaterThan(Integer value) {
            addCriterion("sa_day >", value, "saDay");
            return (Criteria) this;
        }

        public Criteria andSaDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("sa_day >=", value, "saDay");
            return (Criteria) this;
        }

        public Criteria andSaDayLessThan(Integer value) {
            addCriterion("sa_day <", value, "saDay");
            return (Criteria) this;
        }

        public Criteria andSaDayLessThanOrEqualTo(Integer value) {
            addCriterion("sa_day <=", value, "saDay");
            return (Criteria) this;
        }

        public Criteria andSaDayIn(List<Integer> values) {
            addCriterion("sa_day in", values, "saDay");
            return (Criteria) this;
        }

        public Criteria andSaDayNotIn(List<Integer> values) {
            addCriterion("sa_day not in", values, "saDay");
            return (Criteria) this;
        }

        public Criteria andSaDayBetween(Integer value1, Integer value2) {
            addCriterion("sa_day between", value1, value2, "saDay");
            return (Criteria) this;
        }

        public Criteria andSaDayNotBetween(Integer value1, Integer value2) {
            addCriterion("sa_day not between", value1, value2, "saDay");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sampling
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sampling
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}