package com.datacenter.dao;

import com.datacenter.bean.Chinesenews;
import com.datacenter.bean.ChinesenewsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ChinesenewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    int countByExample(ChinesenewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    int deleteByExample(ChinesenewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    int insert(Chinesenews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    int insertSelective(Chinesenews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    List<Chinesenews> selectByExample(ChinesenewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    Chinesenews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Chinesenews record, @Param("example") ChinesenewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Chinesenews record, @Param("example") ChinesenewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Chinesenews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chinesenews
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Chinesenews record);
}