package com.datacenter.dao;

import com.datacenter.bean.Detection;
import com.datacenter.bean.DetectionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface DetectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    int countByExample(DetectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    int deleteByExample(DetectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer reId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    int insert(Detection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    int insertSelective(Detection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    List<Detection> selectByExample(DetectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    Detection selectByPrimaryKey(Integer reId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Detection record, @Param("example") DetectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Detection record, @Param("example") DetectionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Detection record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table detection
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Detection record);
    List<Detection> selectByUrl(String reUrl);//自己写的，通过detection表的url进行查询
  

   
}