package com.datacenter.dao;

import com.datacenter.bean.Geturl;
import com.datacenter.bean.GeturlExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface GeturlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    int countByExample(GeturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    int deleteByExample(GeturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer urlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    int insert(Geturl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    int insertSelective(Geturl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    List<Geturl> selectByExample(GeturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    Geturl selectByPrimaryKey(Integer urlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Geturl record, @Param("example") GeturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Geturl record, @Param("example") GeturlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Geturl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table geturl
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Geturl record);
    
}