package com.datacenter.dao;

import com.datacenter.bean.Newsall;
import com.datacenter.bean.NewsallExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface NewsallMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int countByExample(NewsallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int deleteByExample(NewsallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int insert(Newsall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int insertSelective(Newsall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    List<Newsall> selectByExampleWithBLOBs(NewsallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    List<Newsall> selectByExample(NewsallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    Newsall selectByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Newsall record, @Param("example") NewsallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Newsall record, @Param("example") NewsallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Newsall record, @Param("example") NewsallExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Newsall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Newsall record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table newsall
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Newsall record);
    
    int selectByDate(String newsData);

    //@Select("Select count(*) from newsall where news_modal=#{newsModal}")
    int selectByModel(@Param("newsModal")String newsModal);

    List<Integer> selectByNewsType();//根据news_type返回不同的种类

    List<String> groupByNewsType();//根据news_type返回不同的种类的数量

    List<String> groupByNewsModal();//根据news_modal返回不同的种类

    List<Integer> selectByNewsModal();//根据news_modal返回不同的种类的数量

    List<Integer> groupByMonth();//根据month返回数量

    List<Integer> groupModalByMonth(@Param("newsModal")String newsModal);//根据month返回不同的种类的数量
}