package com.datacenter.dao;

import com.datacenter.bean.Sampling;
import com.datacenter.bean.SamplingExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface SamplingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    int countByExample(SamplingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    int deleteByExample(SamplingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer saId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    int insert(Sampling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    int insertSelective(Sampling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    List<Sampling> selectByExample(SamplingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    Sampling selectByPrimaryKey(Integer saId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Sampling record, @Param("example") SamplingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Sampling record, @Param("example") SamplingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Sampling record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sampling
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Sampling record);
    List<Sampling> selectByUrl(String saUrl);//自己写的，通过detection表的url进行查询
}